[build]
  publish = ".next"
  command = "bun run build"

[build.environment]
  TZ = "Europe/Lisbon"
  NODE_VERSION = "20.9.0"
  NEXT_VERSION = "14.2.3"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
