[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.12.0"
  NEXT_VERSION = "13.4.19"
  TZ='Europe/Lisbon'

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

